//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "client_therapist")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub client_id: Uuid,
    pub therapist_id: Uuid,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::client::Entity",
        from = "Column::ClientId",
        to = "super::client::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Client,
    #[sea_orm(
        belongs_to = "super::therapist::Entity",
        from = "Column::TherapistId",
        to = "super::therapist::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Therapist,
}

impl Related<super::client::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Client.def()
    }
}

impl Related<super::therapist::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Therapist.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
