//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::client::Entity as Client;
pub use super::client_therapist::Entity as ClientTherapist;
pub use super::therapist::Entity as Therapist;
