//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "client_status")]
pub enum ClientStatus {
    #[sea_orm(string_value = "InTherapy")]
    InTherapy,
    #[sea_orm(string_value = "OnHold")]
    OnHold,
    #[sea_orm(string_value = "Completed")]
    Completed,
    #[sea_orm(string_value = "Canceled")]
    Canceled,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "role")]
pub enum Role {
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "Contractor")]
    Contractor,
    #[sea_orm(string_value = "FullTime")]
    FullTime,
    #[sea_orm(string_value = "TeamLead")]
    TeamLead,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "therapist_status")]
pub enum TherapistStatus {
    #[sea_orm(string_value = "Active")]
    Active,
    #[sea_orm(string_value = "Inactive")]
    Inactive,
}
